services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Autowiring
  Ang3\Bundle\AwsPollyBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources}'

  # Poly client
  Aws\Polly\PollyClient:
    arguments:
      -
        version: '%env(resolve:AWS_POLLY_VERSION)%'
        region: '%env(resolve:AWS_POLLY_REGION)%'
        credentials:
          key: '%env(resolve:AWS_POLLY_KEY)%'
          secret: '%env(resolve:AWS_POLLY_SECRET)%'
  ang3.aws_polly.client:
    alias: Aws\Polly\PollyClient
    public: true