services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Autowiring
  Ang3\Bundle\AwsPollyBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources}'

  # Poly client
  Aws\Polly\PollyClient:
    arguments:
      -
        version: '%ang3.aws_polly.version%'
        region: '%ang3.aws_polly.region%'
        credentials:
          key: '%env(AWS_ACCESS_KEY_ID)%'
          secret: '%env(AWS_SECRET_ACCESS_KEY)%'
  ang3.aws_polly.client:
    alias: Aws\Polly\PollyClient
    public: true

  # Speech synthesizer
  Ang3\Bundle\AwsPollyBundle\Service\SpeechSynthesizer:
    arguments:
      $region: '%ang3.aws_polly.region%'
  ang3.aws_polly.speech_synthesizer:
    alias: Ang3\Bundle\AwsPollyBundle\Service\SpeechSynthesizer
    public: true